Initial commit
koninklijke-collective/koning_template pull request #1
Opened 2016-12-01 20:15 UTC by jp1987

2016-12-04 13:57 UTC, jp1987 commented on Configuration/TypoScript/Base/Page.txt
> +    footerData {
@bmoex, weet jij een betere manier om css in de footer te krijgen? includeCSSFooter werkt niet :(

2016-12-12 09:52 UTC, bmoex requested changes

2016-12-12 09:52 UTC, bmoex commented on .gitignore
> +Resources/Public/Css/*.css*
waarom die trailing *?

2016-12-12 09:52 UTC, bmoex commented on Build/package.json
> +  "name": "blog",
TYPO3 template

2016-12-12 09:52 UTC, bmoex commented on Configuration/TSConfig/Page.txt
> +<INCLUDE_TYPOSCRIPT: source="DIR: ./Page/">
extension meegeven? .ts

2016-12-12 09:52 UTC, bmoex commented on Configuration/TSConfig/Page/TCEMAIN.txt
> +    group = 31
31?

2016-12-12 09:52 UTC, bmoex commented on Configuration/TypoScript/constants.txt
> +<INCLUDE_TYPOSCRIPT: source="FILE: EXT:sourceopt/Configuration/TypoScript/constants.txt">
.ts extensie gebruiken aub

2016-12-12 09:52 UTC, bmoex commented on Configuration/TypoScript/setup.txt
> +<INCLUDE_TYPOSCRIPT: source="DIR: ./Base/" extensions="txt">
.ts extensie gebruiken aub

2016-12-12 09:52 UTC, bmoex commented on Configuration/TypoScript/Base/Page.txt
> +plugin.tx_felogin_pi1._CSS_DEFAULT_STYLE >
moet dit hier?

2016-12-12 09:52 UTC, bmoex commented on Resources/Private/Sass/_bootstrap.scss
> +@import "../../../Build/node_modules/bootstrap-sass/assets/stylesheets/bootstrap/responsive-utilities";
waarom niet gewoon `@import "../../../Build/node_modules/bootstrap-sass/assets/stylesheets/bootstrap"`?

2016-12-12 09:52 UTC, bmoex commented on ext_emconf.php
> +            'typo3' => '6.2.0-8.99.99',
7.6.0 minimum

2016-12-12 09:52 UTC, bmoex commented on ext_emconf.php
> +    'title' => 'Base template',
Template: Koning Bootstrap Template

2016-12-12 09:52 UTC, bmoex commented on ext_tables.php
> +\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::appendToTypoConfVars('BE', 'defaultUserTSconfig', '
vind dit niet horen hier, maar in de /Configuration/TSConfig/User/default.ts

2016-12-12 09:53 UTC, jp1987 commented on Resources/Private/Sass/_bootstrap.scss
> +@import "../../../Build/node_modules/bootstrap-sass/assets/stylesheets/bootstrap/responsive-utilities";
Omdat je nu zelf bepaalde componenten aan/uit kan zetten.

2016-12-12 09:53 UTC, jp1987 commented on .gitignore
> +Resources/Public/Css/*.css*
voor style.css en style.css.gz

2017-03-11 11:06 UTC, bmoex approved these changes

2017-03-11 11:06 UTC, merged